name: Deploy React to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: Frontend/my-profile
        run: npm ci

      - name: Build Vite app
        working-directory: Frontend/my-profile
        run: npm run build
      - name: 🔍 List dist folder contents
        run: ls -R Frontend/my-profile/dist
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Frontend/my-profile/dist


